- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8081

  rules:
    - name: Say Hello
      condition: event.payload.message != 0

      action:
        run_job_template:
          name: "Send notification"
          organization: Default
          post_events: true
